### PR TITLE
refactored the GeneratePKCS10 function to work with BouncyCastle inst…

### PR DESCRIPTION
**Pull request by zglozman**
changed the generatePKCS to use bouncycastle instead of java.security, also added shouldRetry to read which is useful for checking if an object already exists in the vault.

### CODE REVIEW

**Comment by steve-perkins** [comment]
Oh, thanks so much!  Yesterday evening, I had started the process of refactoring out that `sun.security.pkcs10.PKCS10` dependency (so the code would work with OpenJDK).  But it was a pain, because the BouncyCastle documentation can be a bit lacking, and the subject matter is so cryptic (pardon the pun).  This saves a lot of hassle.

**Comment by zglozman** [comment]
whats the status with the mount and the sys api ?

**Comment by steve-perkins** [comment]
Can you be more specific?  

There's an existing PR (#72) for listing the mounts... but it enough conflicts and issues that it won't get merged anywhere near its current form, and it appears to be abandoned since last July.  I'll probably circle around to implement that endpoint myself someday (or anyone from the community is welcome to do so), just so I can close that out.

I'm not sure what you mean by "the sys api".  EVERYTHING under `/sys`?  That will definitely be awhile!  :)

**Comment by zglozman** [comment]
Well, I think we need to add (a) function to check if something is mounted, (b) mount a new partition, check if a role exists, and if not create it. so all of the bootstrap logic. I will be happy to implement it if you agree I think is pretty straightforward.  If so let's discuss voice. 

From a housekeeping perspective, I have a small issue, a need a maven repo, of some staging version that incorporates my changes, until they become production so I can use them in the project without publishing my own repo.,  

Another direction to think about is a spring type injection of configuration parameters into there respected classes.

**Pull request merged**
