### PR TITLE
Mounts implementation

### PR DESCRIPTION
**Pull request by flozano**
I can't make the integration tests work, I get always 'connection refused' from the client. I'm using Mac with docker-machine.

Without the ability to test-integrate it, I'm not sure how to proceed from here.

### CODE REVIEW

**Comment by steve-perkins** [comment]
Thanks for the PR!

I was able to close your fork and run the integration tests, but I did have some Docker-related issues doing so.  I'm not sure what's going on.  I'm currently unable to run the tests on my host machine, but when I spin up a quick Ubuntu VM I can run them inside of that just fine.  This brittleness is concerning, I'll have to look into it.

At any rate, I added a few review comments to the code diff.

**Comment by flozano** [comment]
I can't see the review comments... am I missing something? :)

**Comment by steve-perkins** [comment]
Oh, sorry.  I usually just click the "Single Comment" button when leaving comments, but it looks like this time I clicked the "Start Review" button and failed to save the review afterwards.

**Comment by steve-perkins** [comment]
Hi @flozano -

I'm cleaning the project's open issues and PR's, and wanted to touch base.  It looks like the integration test suite was in a bad place when you were working in this PR, and that's probably the prime reason why it stalled out.  

I have just completed a major overhaul of the integration test suit (see pull request #83), and it should run reliably now.  If you're still interested in this PR, I'd love to pull it in if you could take a look at the three comments above.  If not, then I'll try to get around to adapting the code myself at some point.

Thanks!

**Comment by zglozman** [comment]
Hey goes, i am not using logical to work around this issue, but ultimately i think we need to implement higher level functions for mount, sys api and everything else

**Comment by khos2ow** [comment]
@steve-perkins any updates on this PR? if not I can pull the code from here to my fork and try to finish it up.

**Pull request closed without merging**
