### PR TITLE
Add kubernetes auth method

### PR DESCRIPTION
**Pull request by seanmalloy**
This is a work in progress. I'm not really a Java programmer. I have not tested this code yet. I'll be testing this code in a next few days.

Any feedback on this pull request would be greatly appreciated.

https://www.vaultproject.io/docs/auth/kubernetes.html

### CODE REVIEW

**Comment by seanmalloy** [comment]
I have it compiling now. Both of the below commands now execute with out error.

```
$ ./gradlew build
$ ./gradlew jar
```

Next step is to test it to see if if works.

**Comment by seanmalloy** [comment]
I have successfully tested the code, and it working now. Ready for review.

**Comment by seanmalloy** [comment]
@steve-perkins this PR is now ready for review. Let me know if any changes are needed.

**Comment by seanmalloy** [comment]
Here is the example program I created for testing this.

```java
/*
 *
 * javac -cp ".:/home/sean/projects/vault-java-driver/build/libs/vault-java-driver-3.1.0.jar" HelloWorld.java 
 * java -cp ".:/home/sean/projects/vault-java-driver/build/libs/vault-java-driver-3.1.0.jar" HelloWorld
 *
 */
import com.bettercloud.vault.*;
import java.nio.file.*;

public class HelloWorld {

    public static void main(String[] args) throws Exception {
	final VaultConfig config = new VaultConfig().address("http://192.168.1.193:8200").build();
	final Vault vault = new Vault(config);

	// read kube jwt from file
	String jwt = new String(Files.readAllBytes(Paths.get("/var/run/secrets/kubernetes.io/serviceaccount/token")));
	System.out.print(jwt);

	// get vault token
	String token = vault.auth().loginByKubernetes("demo", jwt, "foo").getAuthClientToken();

	System.out.print(token);
    }

}
```

**Comment by casz** [comment]
@seanmalloy seems #164 is the better approach? reusing what was already there with JWT knowledge :sweat:

**Comment by seanmalloy** [comment]
@casz I agree #164 looks better, has less code duplication. I'll leave this open, so the project maintainer can decide which approach they like best.

**Comment by casz** [comment]
Duplicate of #164

**Comment by steve-perkins** [comment]
Thanks, @seanmalloy!  We've had a number of PR's for this popular feature!  It was ultimately merged as part of #164, and will go out to Maven Central in the next couple of days.

**Pull request closed without merging**
