### PR TITLE
Support for auth within Kubernetes and generic JWT

### PR DESCRIPTION
**Pull request by mrunesson**
Support using JWT token for Kubernetes service account to
authenticate. Since both GCP and Kubernetes uses JWT, refactored to
also offer generic JWT support to be used by aginst other JWT
based authentication services.

### CODE REVIEW

**Comment by casz** [comment]
@steve-perkins @jarrodcodes friendly poke, we would love to see this integrated.

https://github.com/jenkinsci/configuration-as-code-plugin/issues/828

**Comment by mpluhar** [comment]
Hi there, any updates on this? We would really like to use kubernetes auth.

**Comment by roidelapluie** [comment]
@steve-perkins friendly poke again..

**Comment by kunickiaj** [comment]
Any chance of getting this merged, to avoid another fork?
🤞

**Comment by casz** [comment]
I tried reaching out via email and asking if they need a maintainer or if they would at least take care of this PR.

If nothing else I guess we are down to forking :cry:

**Comment by jedidiahB** [comment]
@casz 
I had to open a support case with bettercloud to get their attention to merge earlier this year.
https://support.bettercloud.com/hc/en-us

**Comment by casz** [comment]
@jedidiahB well they should perhaps reconsider their company name :trollface:

**Comment by steve-perkins** [comment]
Apologies for the delay.  Note that this is an "evenings-and-weekends" initiative by one, occasionally two volunteers, and bandwidth has been less-than-zero for the past quarter for reasons both professional and family-related.  Please do not send tickets to customer support.  They're great people, but they work on the customer-facing web product, and are not familiar with side projects bubbling out of the engineering team.  It only creates difficulties for other developers releasing code in the future.

I would not be offended at all by any forks made from the codebase.  We ourselves use a proprietary fork of an older version, because we don't need the more recent features contributed by the community, and want to avoid the impact of changing everything whenever an API breakage requires a major version bump.  

However, I do intend to continue maintenance of this root repository.  I understand that the `master` branch has been quiet since February, and there is a queue of contributed PR's pending review.  My goal is to work through that review queue on at least a quarterly cadence, cutting new Maven Central releases every 3-6 months depending on what's been added.

@mrunesson:  Thanks for the contribution!  I plan to work through the open PR's over the next couple of days and cut a new Maven Central release.  I'll know whether it's a minor version change or major version bump once I see whether there are any API breaking changes.  The logic in this PR looks extremely straightforward, but there's not an integration test (and understandably so, since it would require a Kubernetes environment).  Have you manually tested your build against a k8s cluster?

Closing #171 as redundant.

**Comment by casz** [comment]
@steve-perkins thanks :) You should not have to explain. The non-response is what I find troublesome. 
A simple we are busy, or we'll get back to you. Will do just fine.

**Pull request merged**
