### PR TITLE
Token creation against roles and createToken refactor

### PR DESCRIPTION
**Pull request by schulzh**
I've added a builder pattern class ```TokenRequest``` for easier use (and expandability) of the token creation methods and, with it, the ability to create tokens against a role (https://github.com/BetterCloud/vault-java-driver/issues/27)

### CODE REVIEW

**Comment by steve-perkins** [comment]
Thanks so much for the pull request!  Apologies for the delay in getting in reviewed.

This looks good to me, but there's currently a merge conflict.  Could you please update it so it will merge cleanly?

**Comment by alexku-o** [comment]
Thanks for the work!

I could be missing something, but should there not be updated tests for this PR? Or maybe  https://github.com/BetterCloud/vault-java-driver/blob/master/src/test-integration/java/com/bettercloud/vault/api/AuthTests.java at the very least?

**Comment by steve-perkins-bc** [comment]
Back when we had zero community contributors outside of my company, I developed some bad habits to encourage more contributors to step forward.  When PR's came through without a test case, I would typically just write it myself rather than be a stickler and send the PR back.

Now with 14 contributors and climbing, maybe it's time to tighten up and insist on test coverage.

**Comment by schulzh** [comment]
Sorry for my late response, I did not get a notification email for some reason...

Regarding the tests, one could argue that the coding is already tested by the refactoring of the original createToken() method (which internally now uses the TokenRequest class), but I've replicated the unit test to additionally use token request directly.

**Comment by schulzh** [comment]
I could also add a unit test which tests creating a token with a role, but that would require setting up a role in vault beforehand...

**Comment by steve-perkins** [comment]
Thank you so much for the submission!  I'm not too concerned about complete test coverage right this moment... because as soon as we PR #25 merged, then I'll be re-doing all of the tests to use a Dockerized instance of Vault instead of the current tedious manual setup.

**Pull request merged**
